name: moreinfo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  image_picker: ^0.8.4+9
  charts_flutter: ^0.12.0
  location: ^4.3.0
  provider: ^6.0.1
  flutter_spinkit: ^5.1.0
  google_maps_flutter: ^2.1.1
  dio: ^4.0.4
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^7.6.1
  intl: ^0.17.0
  editable: ^2.0.0
  multi_select_flutter: ^4.1.2
  file_picker: ^4.1.2
  flutter_sound: ^9.1.7
  permission_handler: ^9.0.2
  audio_session: ^0.1.6+1
  open_file: ^3.2.1
  restart_app: ^1.1.0
  device_info: ^2.0.3
  path_provider: ^2.0.9
  image_gallery_saver: ^1.7.1
  intro_slider: ^3.0.4
  pull_to_refresh: ^2.0.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:
  json_serializable: ^6.1.4
  flutter_launcher_icons: ^0.9.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"
